version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: contacts
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 3309:5432

  db_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: contacts_test
    volumes:
      - ./data_test:/var/lib/postgresql/data
    ports:
      - 3310:5432
